[package]
name = "kitten_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotly = { version = "0.8.3", features = ["kaleido"] }
rand = "0.8.5"
rand_distr = "0.4.3"
timeit = "0.1.2"
